### PR TITLE
fix rounding glitch for brightness and contrast in config dialog

### PR DESCRIPTION
**Pull request by AlphaLima**
fixed this:
http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=8718

### CODE REVIEW

**Comment by brunotl** [comment]
why removing iround() call ?

**Comment by pventafridda** [comment]
TerrainBrightness is a SHORT, not a float. We ought to use iround.
The problem you try to fix may be instead related to the SetAsFloat.

**Comment by AlphaLima** [comment]
I don't mind. I don't want to investigate the real cause of it and I can live with the glitch.

**Comment by AlphaLima** [comment]
OK, made it with iround!

**Comment by pventafridda** [comment]
I merge it now. Ulli please ensure it works properly!

**Pull request merged**
