### PR TITLE
Increment Android version

### PR DESCRIPTION
**Pull request by brunotl**

### CODE REVIEW

**Comment by pventafridda** [comment]
Do we upgrade VERSION in Define now as well?

From: Bruno de Lacheisserie 
Sent: Friday, March 10, 2017 7:24 PM
To: LK8000/LK8000 
Cc: Subscribed 
Subject: [LK8000/LK8000] Increment Android version (#1067)


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/LK8000/LK8000/pull/1067

Commit Summary
  a.. Increment Android version 
File Changes
  a.. M android-studio/app/build.gradle (4) 
Patch Links:
  a.. https://github.com/LK8000/LK8000/pull/1067.patch 
  b.. https://github.com/LK8000/LK8000/pull/1067.diff

**Comment by brunotl** [comment]
define already have right version

**Comment by pventafridda** [comment]
ok great thx

**Comment by pventafridda** [comment]
the right version for a beta is not e0, it is simply "e"  . 0 stands for alpha.

**Pull request merged**
