### PR TITLE
Kobo Aura 2 edition

### PR DESCRIPTION
**Pull request by brunotl**

### CODE REVIEW

**Comment by pventafridda** [comment]
what the hell ?? I did the pull, merged and push back. Commits showing in the code list, but still the pull request is here.

**Comment by brunotl** [comment]
because this pull request is for V6 branch ....

image

**Comment by pventafridda** [comment]
damn right-
anything I can do ? I see you removed the pull

**Comment by brunotl** [comment]
No problem, i Will make another later

**Pull request closed without merging**
