### PR TITLE
Merge pull request #1 from LK8000/master

### PR DESCRIPTION
**Pull request by SergioDaSilva82**
Update June 14

### CODE REVIEW

**Comment by pventafridda** [comment]
bravo. In fact you got the problem with master. You need to make your branch to work on.

**Comment by SergioDaSilva82** [comment]
I am so newbie on this, I will try my luck :)

**Comment by pventafridda** [comment]
from nimbus:
branch –b sergio

then you are working in the branch named sergio
you do the commit of your fixes

commit –a

then you make the pull request

**Comment by SergioDaSilva82** [comment]
I was trying to do it online :)

I will try from nimbus

**Pull request closed without merging**
