### PR TITLE
V51

### PR DESCRIPTION
**Pull request by brunotl**
----------------
- Version 5.1A - 
----------------

Screen : 
  - Transpareny for bottom bar and airspace drawing can be use on all device
  - Screen rotate feature inside LK turn only LK8000 display orientation, orientation of device shell is restored on LK8000 shutdown  

Glide computer : 
  - Aispeed accuracy for Glider polar is now 0.5m/s instead of 1m/s previously
  - Improved accuracy of Speed to Fly calculation

Task :
  - New Conical ESS turnpoint type for PG optimized task
      Best speed / climb rate for reach this turnpoint is displayed inside analysis / glidepolar screen.
      Cone slope is draw on next turnpoint "side view".
      AutoMC and Speed to fly take account of Conical ESS in Final Glide.
      Default "Base Altitude" for this turnpoint is Altitude of turnpoint.
  - Requiered speed for reach start on Time Gate Overlay, 
      "---" is diplayed when speed is to slow, "oo" when speed is too fast.

Simulator : 
  - New netto vario parameter in integrated simulator.
 
Auto Zoom : 
  - Now autozoom is calcuated using "optimized turnpoint" (or AAT Target point) instead of center previously.

### CODE REVIEW

**Comment by SergioDaSilva82** [comment]
Is it possible to merge this code soon? Some of the improvements are really good to give a try

**Comment by pventafridda** [comment]
I strongly discourage merging new code into the master right now.
We have way too many things to fix already. If we merge those changes the whole code will need MONTHS of retesting.
Right now all calculations are those of v5, which means that if something is strange we have something to fix in the porting, not in the new code.
If we merge, we shall never know if it is a problem of the new code, or in the porting of old. 
At least we must exit alpha stage, which means that for us everything is ok.
Then we can merge.

**Comment by SergioDaSilva82** [comment]
OK Paolo ;) I understand the issues about merging new code

**Comment by brunotl** [comment]
it's exactly what, i have explained some time ago ...

**Comment by SergioDaSilva82** [comment]
I know Bruno, but I wanted an "official" version to answer this: http://www.paraglidingforum.com/viewtopic.php?p=p450031#p450031

Relax ;)

**Comment by pventafridda** [comment]
I think it wont take so long to end alpha stage, Sergio.
We are progressing quickly. Thanks to the fact that we are using the stable code. Any glitch is related to porting, and quite fast to fix.

**Comment by SergioDaSilva82** [comment]
I think is time to merge this code to the master since new features were already added in the code,  like font size,  bottom bar and others. So I don't see any reason to not merge this code also.

We already in beta stage.

**Comment by pventafridda** [comment]
I dont think so.

**Comment by brunotl** [comment]
why ?

**Comment by pventafridda** [comment]
because before merging we need to check what happens also to glider, if I dont remember wrong. I suggest we advance to a new beta, and then we dedicate the other one to this merge.

**Comment by pventafridda** [comment]
.. then I am working on the last on-off switch for overlays, and I'd like to finish it by the weekend..

**Comment by SergioDaSilva82** [comment]
I just think sooner we release it more time the pilots have to test it.

**Comment by pventafridda** [comment]
It cannot be merged as it is, so more time is required to fix the changes for current master.

**Comment by SergioDaSilva82** [comment]
Bruno,  can you fix it?

**Comment by brunotl** [comment]
Already done by me & for me...

**Comment by brunotl** [comment]
cf. https://github.com/brunotl/LK8000/commits/_road_to_linux

**Comment by SergioDaSilva82** [comment]
@brunotl I might compile one version for Kobo using your branch and share it and wait for feedback

**Comment by pventafridda** [comment]
Good idea. Please check also with some hundreds glider pilots, since they are all affected by changes.

**Comment by SergioDaSilva82** [comment]
@pventafridda I am going to ask Bruno to merge the latest commits you put in the master. Then I will compile it.

**Comment by pventafridda** [comment]
Please do not use the version 5.3 but another name ("road to linux" or sergio or what you like).
Let's not create confusion on versions.

**Comment by pventafridda** [comment]
I think we have merged most of this, if not all, in master. But I am not sure.

**Comment by brunotl** [comment]
all are merged in master branch !

**Pull request closed without merging**
