### PR TITLE
Show Black circle for static Flarm-Objects

### PR DESCRIPTION
**Pull request by gereic**
Changed icons for static Flarm-Object (on ground-pilots) to black circle.
A static object (ground-object) is determined, when speed is 0 according to flarm data port specification

<GroundSpeed> Decimal integer value. Range: from 0 to 32767.
When the aircraft is considered moving, the target’s ground
speed in m/s, forced to > 0.
When the aircraft is considered on the ground, the field is
forced to 0.
This field is empty if stealth mode is activated either on the
target or own aircraft and for non-directional targets.

### CODE REVIEW

**Comment by brunotl** [comment]
you need to rebase your branch on top of upstream before doing a pull request...

**Comment by gereic** [comment]
It says, the bransch is already up to date.

git pull --rebase origin master
From https://github.com/gereic/LK8000
 * branch                master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.

**Comment by brunotl** [comment]
you need to rebase on upstream not on origin...

**Comment by gereic** [comment]
I tried to rebase.
Can you check if pull-Request is ok now ?

**Comment by brunotl** [comment]
53 commit in pull-request, that can't be good ...

**Comment by gereic** [comment]
I have only changed 2 Files.
What should I do ??
Should I create a new fork and implement the changes again ?

**Comment by brunotl** [comment]
to fix your pull-request, the simpler is  : 

set your local copy to head of upstream/master
```git checkout upstream/master```
create new branch named "fanet-work"
```git branch fanet-work```
set your local copy to new branch
```git checkout fanet-work```
merge your work inside your local copy
```git merge gereic/master --no-commit --ff --squash```
cleanup all unwanted change 
when every is ok, commit push to origin and do a new pull request ...

**Pull request closed without merging**
