### PR TITLE
Download Manager : Add Hi-Res maps from lotnik.org

### PR DESCRIPTION
**Pull request by RyszardLewandowski**
- High resolution maps (topology with forest, topology without forest, DEM ) for Chech Republic, Lithuania, Slovakia.
- High resolution topology without forest for Poland.

### CODE REVIEW

**Review by brunotl — CHANGES_REQUESTED** [review]
can't be merged as is, files must be hosted on https website ...

**Comment by RyszardLewandowski** [comment]
But as previous (in current version) you accepted http with my files . I'm
changing configuration but it will take a few months...
--
Regards
Ryszard Lewandowski


https://www.facebook.com/ryszard.lewandowski.921
http://www.microaviator.pl
https://www.facebook.com/MicroAviator
<https://www.facebook.com/pages/MicroAviatorpl/184548324970027>/


śr., 4 wrz 2024 o 10:41 Bruno de Lacheisserie ***@***.***>
napisał(a):

**Comment by brunotl** [comment]
yes i know, but that require to setup a security exception because http not allowed on modern android device.
this is exception was bad idea. 

your web site look to be hosted on "aftermarket.pl" and https is a simple option on this provider : https://www.aftermarket.pl/pomoc/pl/hosting/domeny/jak_uzyskac_darmowy_certyfikat_ssl_lets_encrypt_dla_domeny.htm

**Comment by RyszardLewandowski** [comment]
No, I have my own VPS servers. Aftermarket.pl is only a DNS server.
--
Regards
Ryszard Lewandowski


https://www.facebook.com/ryszard.lewandowski.921
http://www.microaviator.pl
https://www.facebook.com/MicroAviator
<https://www.facebook.com/pages/MicroAviatorpl/184548324970027>/


śr., 4 wrz 2024 o 11:35 Bruno de Lacheisserie ***@***.***>
napisał(a):

**Comment by brunotl** [comment]
nginx / cerbot / let's encrypt is also simple to setup, or if you prefer, we can put the files on lk8000.it web site ...

**Comment by RyszardLewandowski** [comment]
The airspaces files are produced twice a day. The map files every 30 days.
I have a lot of scripts on my server to do that. So - I can't just put it
on your server. Unfortunately, my nginx is working with
extremely complicated configuration (one instance supports 30+ domains) -
so it's not so easy...

Ok, if it's a problem - just delete my files.
--
Regards
Ryszard Lewandowski


https://www.facebook.com/ryszard.lewandowski.921
http://www.microaviator.pl
https://www.facebook.com/MicroAviator
<https://www.facebook.com/pages/MicroAviatorpl/184548324970027>/


śr., 4 wrz 2024 o 11:56 Bruno de Lacheisserie ***@***.***>
napisał(a):

**Comment by brunotl** [comment]
i will merge this, but please upgrade your server to support https ...

**Comment by RyszardLewandowski** [comment]
Thanks, I already installed https. I will prepare another 3 HiRes maps - so
I will change all the addresses.
--
Regards
Ryszard Lewandowski


niedz., 8 wrz 2024 o 13:34 Bruno de Lacheisserie ***@***.***>
napisał(a):

**Pull request merged**
