### PR TITLE
last fix

### PR DESCRIPTION
**Pull request by brunotl**

### CODE REVIEW

**Comment by pventafridda** [comment]
I spent literally hours to test 11025 22050 44100 on SDL . And the problem is that resampling will not always maintain the original sound volume and quality. All the sounds are custom in fact, not stuff found on the internet.  So I am a bit worried: how did you test the 22050 and compared to the current SDL latency problem?


From: Bruno de Lacheisserie 
Sent: Saturday, August 29, 2015 9:50 AM
To: LK8000/LK8000 
Subject: [LK8000] last fix (#751)


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/LK8000/LK8000/pull/751

Commit Summary
  a.. Resample sound to 22050 Hz for compatibility with linux. 
  b.. add LK8000-PC_debug-ns.exe & LK8000-PC_debug.exe to .gitignore 
  c.. update makeall script 
  d.. savelk.sh : fix typo mistake 
  e.. Memory Canvas : fix DrawOutlineRectangle 
  f.. dlgProgress : fix missing hollow brush selection. 
  g.. safe_delete() use nullptr instead of 0 
  h.. MapWindow::CalculateScreenBounds : remove useless sqrt() call 
File Changes
  a.. M .gitignore (72) 
  b.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME1.WAV (0) 
  c.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME12.WAV (0) 
  d.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME12F.WAV (0) 
  e.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME1B.WAV (0) 
  f.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2.WAV (0) 
  g.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME21.WAV (0) 
  h.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2B.WAV (0) 
  i.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2C.WAV (0) 
  j.. M Common/Distribution/LK8000/_System/_Sounds/DROPMARKER.WAV (0) 
  k.. T Common/Distribution/LK8000/_System/_Sounds/LK_3HITONES.WAV (0) 
  l.. M Common/Distribution/LK8000/_System/_Sounds/LK_AIRSPACE.WAV (0) 
  m.. M Common/Distribution/LK8000/_System/_Sounds/LK_AIRSPACEV3.WAV (0) 
  n.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT1.WAV (0) 
  o.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT2.WAV (0) 
  p.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT3.WAV (0) 
  q.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_DOUBLE2.WAV (0) 
  r.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_SHORT.WAV (0) 
  s.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_SKULLED.WAV (0) 
  t.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_WARPED.WAV (0) 
  u.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP0.WAV (0) 
  v.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP1.WAV (0) 
  w.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP4.WAV (0) 
  x.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP6.WAV (0) 
  y.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP9.WAV (0) 
  z.. T Common/Distribution/LK8000/_System/_Sounds/LK_BELL.WAV (0) 
  aa.. M Common/Distribution/LK8000/_System/_Sounds/LK_BLIP.WAV (0) 
  ab.. M Common/Distribution/LK8000/_System/_Sounds/LK_BOOSTER.WAV (0) 
  ac.. M Common/Distribution/LK8000/_System/_Sounds/LK_CHIME.WAV (0) 
  ad.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECT.WAV (0) 
  ae.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECTV2.WAV (0) 
  af.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECTV3.WAV (0) 
  ag.. T Common/Distribution/LK8000/_System/_Sounds/LK_DINGDONG.WAV (0) 
  ah.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECT.WAV (0) 
  ai.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECTV2.WAV (0) 
  aj.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECTV3.WAV (0) 
  ak.. M Common/Distribution/LK8000/_System/_Sounds/LK_FREEFLIGHT.WAV (0) 
  al.. M Common/Distribution/LK8000/_System/_Sounds/LK_GATEOPEN.WAV (0) 
  am.. M Common/Distribution/LK8000/_System/_Sounds/LK_GEARWARNING.WAV (0) 
  an.. T Common/Distribution/LK8000/_System/_Sounds/LK_GPSNOCOM.WAV (0) 
  ao.. T Common/Distribution/LK8000/_System/_Sounds/LK_GPSNOFIX.WAV (0) 
  ap.. T Common/Distribution/LK8000/_System/_Sounds/LK_GREEN.WAV (0) 
  aq.. T Common/Distribution/LK8000/_System/_Sounds/LK_HITONE.WAV (0) 
  ar.. M Common/Distribution/LK8000/_System/_Sounds/LK_LANDING.WAV (0) 
  as.. T Common/Distribution/LK8000/_System/_Sounds/LK_LONGHITONE.WAV (0) 
  at.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER1.WAV (0) 
  au.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER2.WAV (0) 
  av.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER3.WAV (0) 
  aw.. M Common/Distribution/LK8000/_System/_Sounds/LK_PROBLEM.WAV (0) 
  ax.. M Common/Distribution/LK8000/_System/_Sounds/LK_RED.WAV (0) 
  ay.. M Common/Distribution/LK8000/_System/_Sounds/LK_SAFETAKEOFF.WAV (0) 
  az.. M Common/Distribution/LK8000/_System/_Sounds/LK_SDHITONE.WAV (0) 
  ba.. T Common/Distribution/LK8000/_System/_Sounds/LK_SHORTHITONE.WAV (0) 
  bb.. M Common/Distribution/LK8000/_System/_Sounds/LK_SLIDE.WAV (0) 
  bc.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H1.WAV (0) 
  bd.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H2.WAV (0) 
  be.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H3.WAV (0) 
  bf.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H4.WAV (0) 
  bg.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H5.WAV (0) 
  bh.. M Common/Distribution/LK8000/_System/_Sounds/LK_TAKEOFF.WAV (0) 
  bi.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKFINISH.WAV (0) 
  bj.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKPOINT.WAV (0) 
  bk.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKSTART.WAV (0) 
  bl.. T Common/Distribution/LK8000/_System/_Sounds/LK_TICK.WAV (0) 
  bm.. T Common/Distribution/LK8000/_System/_Sounds/LK_TOCK.WAV (0) 
  bn.. M Common/Distribution/LK8000/_System/_Sounds/LK_TONEDOWN.WAV (0) 
  bo.. M Common/Distribution/LK8000/_System/_Sounds/LK_TONEUP.WAV (0) 
  bp.. M Common/Distribution/LK8000/_System/_Sounds/LK_WARNING.WAV (0) 
  bq.. M Common/Distribution/LK8000/_System/_Sounds/LK_WHISTLE.WAV (0) 
  br.. M Common/Distribution/LK8000/_System/_Sounds/TARGVISIBLE.WAV (0) 
  bs.. M Common/Distribution/LK8000/_System/_Sounds/UNLOCKMAP.WAV (0) 
  bt.. M Common/Distribution/LK8000/_System/_Sounds/VOICEDEMO1.WAV (0) 
  bu.. M Common/Source/Dialogs/dlgProgress.cpp (1) 
  bv.. M Common/Source/Draw/CalculateScreen.cpp (11) 
  bw.. M Common/Source/Sound/SDL/Sound.cpp (2) 
  bx.. M Common/Source/utils/stl_utils.h (8) 
  by.. M Common/Source/xcs/Screen/Memory/Canvas.cpp (4) 
  bz.. M makeall (2) 
  ca.. M savelk.sh (2) 
Patch Links:
  a.. https://github.com/LK8000/LK8000/pull/751.patch 
  b.. https://github.com/LK8000/LK8000/pull/751.diff

**Comment by brunotl** [comment]
Si you have made test on real hardware ?

Le 30 août 2015 à 03:04, Paolo Ventafridda <notifications@github.com> a
écrit :

I spent literally hours to test 11025 22050 44100 on SDL . And the problem
is that resampling will not always maintain the original sound volume and
quality. All the sounds are custom in fact, not stuff found on the
internet. So I am a bit worried: how did you test the 22050 and compared to
the current SDL latency problem?


From: Bruno de Lacheisserie
Sent: Saturday, August 29, 2015 9:50 AM
To: LK8000/LK8000
Subject: [LK8000] last fix (#751)


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
https://github.com/LK8000/LK8000/pull/751

Commit Summary
a.. Resample sound to 22050 Hz for compatibility with linux.
b.. add LK8000-PC_debug-ns.exe & LK8000-PC_debug.exe to .gitignore
c.. update makeall script
d.. savelk.sh : fix typo mistake
e.. Memory Canvas : fix DrawOutlineRectangle
f.. dlgProgress : fix missing hollow brush selection.
g.. safe_delete() use nullptr instead of 0
h.. MapWindow::CalculateScreenBounds : remove useless sqrt() call
File Changes
a.. M .gitignore (72)
b.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME1.WAV (0)
c.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME12.WAV (0)
d.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME12F.WAV (0)
e.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME1B.WAV (0)
f.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2.WAV (0)
g.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME21.WAV (0)
h.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2B.WAV (0)
i.. M Common/Distribution/LK8000/_System/_Sounds/CABINCHIME2C.WAV (0)
j.. M Common/Distribution/LK8000/_System/_Sounds/DROPMARKER.WAV (0)
k.. T Common/Distribution/LK8000/_System/_Sounds/LK_3HITONES.WAV (0)
l.. M Common/Distribution/LK8000/_System/_Sounds/LK_AIRSPACE.WAV (0)
m.. M Common/Distribution/LK8000/_System/_Sounds/LK_AIRSPACEV3.WAV (0)
n.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT1.WAV (0)
o.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT2.WAV (0)
p.. T Common/Distribution/LK8000/_System/_Sounds/LK_ALARM_ALT3.WAV (0)
q.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_DOUBLE2.WAV (0)
r.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_SHORT.WAV (0)
s.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_SKULLED.WAV (0)
t.. M Common/Distribution/LK8000/_System/_Sounds/LK_ALERT_WARPED.WAV (0)
u.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP0.WAV (0)
v.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP1.WAV (0)
w.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP4.WAV (0)
x.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP6.WAV (0)
y.. M Common/Distribution/LK8000/_System/_Sounds/LK_BEEP9.WAV (0)
z.. T Common/Distribution/LK8000/_System/_Sounds/LK_BELL.WAV (0)
aa.. M Common/Distribution/LK8000/_System/_Sounds/LK_BLIP.WAV (0)
ab.. M Common/Distribution/LK8000/_System/_Sounds/LK_BOOSTER.WAV (0)
ac.. M Common/Distribution/LK8000/_System/_Sounds/LK_CHIME.WAV (0)
ad.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECT.WAV (0)
ae.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECTV2.WAV (0)
af.. M Common/Distribution/LK8000/_System/_Sounds/LK_CONNECTV3.WAV (0)
ag.. T Common/Distribution/LK8000/_System/_Sounds/LK_DINGDONG.WAV (0)
ah.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECT.WAV (0)
ai.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECTV2.WAV (0)
aj.. M Common/Distribution/LK8000/_System/_Sounds/LK_DISCONNECTV3.WAV (0)
ak.. M Common/Distribution/LK8000/_System/_Sounds/LK_FREEFLIGHT.WAV (0)
al.. M Common/Distribution/LK8000/_System/_Sounds/LK_GATEOPEN.WAV (0)
am.. M Common/Distribution/LK8000/_System/_Sounds/LK_GEARWARNING.WAV (0)
an.. T Common/Distribution/LK8000/_System/_Sounds/LK_GPSNOCOM.WAV (0)
ao.. T Common/Distribution/LK8000/_System/_Sounds/LK_GPSNOFIX.WAV (0)
ap.. T Common/Distribution/LK8000/_System/_Sounds/LK_GREEN.WAV (0)
aq.. T Common/Distribution/LK8000/_System/_Sounds/LK_HITONE.WAV (0)
ar.. M Common/Distribution/LK8000/_System/_Sounds/LK_LANDING.WAV (0)
as.. T Common/Distribution/LK8000/_System/_Sounds/LK_LONGHITONE.WAV (0)
at.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER1.WAV (0)
au.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER2.WAV (0)
av.. T Common/Distribution/LK8000/_System/_Sounds/LK_ORBITER3.WAV (0)
aw.. M Common/Distribution/LK8000/_System/_Sounds/LK_PROBLEM.WAV (0)
ax.. M Common/Distribution/LK8000/_System/_Sounds/LK_RED.WAV (0)
ay.. M Common/Distribution/LK8000/_System/_Sounds/LK_SAFETAKEOFF.WAV (0)
az.. M Common/Distribution/LK8000/_System/_Sounds/LK_SDHITONE.WAV (0)
ba.. T Common/Distribution/LK8000/_System/_Sounds/LK_SHORTHITONE.WAV (0)
bb.. M Common/Distribution/LK8000/_System/_Sounds/LK_SLIDE.WAV (0)
bc.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H1.WAV (0)
bd.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H2.WAV (0)
be.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H3.WAV (0)
bf.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H4.WAV (0)
bg.. M Common/Distribution/LK8000/_System/_Sounds/LK_SONAR_H5.WAV (0)
bh.. M Common/Distribution/LK8000/_System/_Sounds/LK_TAKEOFF.WAV (0)
bi.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKFINISH.WAV (0)
bj.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKPOINT.WAV (0)
bk.. T Common/Distribution/LK8000/_System/_Sounds/LK_TASKSTART.WAV (0)
bl.. T Common/Distribution/LK8000/_System/_Sounds/LK_TICK.WAV (0)
bm.. T Common/Distribution/LK8000/_System/_Sounds/LK_TOCK.WAV (0)
bn.. M Common/Distribution/LK8000/_System/_Sounds/LK_TONEDOWN.WAV (0)
bo.. M Common/Distribution/LK8000/_System/_Sounds/LK_TONEUP.WAV (0)
bp.. M Common/Distribution/LK8000/_System/_Sounds/LK_WARNING.WAV (0)
bq.. M Common/Distribution/LK8000/_System/_Sounds/LK_WHISTLE.WAV (0)
br.. M Common/Distribution/LK8000/_System/_Sounds/TARGVISIBLE.WAV (0)
bs.. M Common/Distribution/LK8000/_System/_Sounds/UNLOCKMAP.WAV (0)
bt.. M Common/Distribution/LK8000/_System/_Sounds/VOICEDEMO1.WAV (0)
bu.. M Common/Source/Dialogs/dlgProgress.cpp (1)
bv.. M Common/Source/Draw/CalculateScreen.cpp (11)
bw.. M Common/Source/Sound/SDL/Sound.cpp (2)
bx.. M Common/Source/utils/stl_utils.h (8)
by.. M Common/Source/xcs/Screen/Memory/Canvas.cpp (4)
bz.. M makeall (2)
ca.. M savelk.sh (2)
Patch Links:
a.. https://github.com/LK8000/LK8000/pull/751.patch
b.. https://github.com/LK8000/LK8000/pull/751.diff
—
Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHub
<https://github.com/LK8000/LK8000/pull/751#issuecomment-136067406>.

**Comment by pventafridda** [comment]
I tested on PC linux, if SDL does not work with a fast PC, it will never work on slower hardware.
Some literature says that the latency is due to a bad implementation of buffering, and a solution is to fill the buffer faster.
I will try to send directly to sound device, bypassing SDL. It cannot be any worst and there is no race condition .

**Comment by brunotl** [comment]
You can revert if you want, but it's better to have all sound at same rates
And un all case 16khz sound don't work
Try takeoff and landing sound on réal hardware ....

Le 30 août 2015 à 12:35, Paolo Ventafridda <notifications@github.com> a
écrit :

I tested on PC linux, if SDL does not work with a fast PC, it will never
work on slower hardware.
Some literature says that the latency is due to a bad implementation of
buffering, and a solution is to fill the buffer faster.
I will try to send directly to sound device, bypassing SDL. It cannot be
any worst and there is no race condition .

**Comment by pventafridda** [comment]
I dont want to revert, only reminder "attention"..
---
Sent from mobile



Il 30 Agosto 2015 12:40:26 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Pull request merged**
