### PR TITLE
TCP device port

### PR DESCRIPTION
**Pull request by brunotl**

### CODE REVIEW

**Comment by pventafridda** [comment]
Do you want to put this in tomorrow's beta or do you want to keep it for 5.3k ?

**Comment by brunotl** [comment]
Has you want, but soon it's tested soon we will know if something is wrong

**Comment by pventafridda** [comment]
But is it testable? I did not merge it yet so I ask without knowing what it does.
Can we feed LK from a smartphone already? Or how do we test it

**Comment by brunotl** [comment]
I have made test with gpsfeed+ And 2 kobo
All work fine.
Not tested on pna because I don't have device with ip stack.

**Comment by pventafridda** [comment]
Then LETS GO in this beta!

**Pull request merged**
