### PR TITLE
changed icon of Flarm-object, which are on ground

### PR DESCRIPTION
**Pull request by gereic**
(speed == 0) to black circle

### CODE REVIEW

**Comment by gereic** [comment]
2 Loops, because of the Z-Level of the objects.
So static objects are always in Background und the flying ones are on Top.

**Comment by brunotl** [comment]
> 2 Loops, because of the Z-Level of the objects.
> So static objects are always in Background und the flying ones are on Top.

it's not obvious reading the code, so comments is required to avoid mistake in future.

a better approch is to sort object by priority using distance / Moving / Static and draw the N first ...

**Comment by gereic** [comment]
Changed the intend,
create more comment.
In order to sort the list, I think it would be good to create (or use the FlarmId.txt) as a Buddy(Friends)-List.
So that the Buddys will prior shown.
Then we can create another choice for showing flarm-traffic on map
- OFF
- only Friends
- All

What do you think about it ?
When this is done, the sorting make sense I think.

**Comment by brunotl** [comment]
2 point : 
- changing the wall code indent and code flow in same commit make code review impossible
- Flarm is made to prevent collision not to do a buddies tracking even if flarm object is used to draw both on map, so filtering object is not a good idea.

**Comment by gereic** [comment]
So what do I have to do now ??

**Comment by gereic** [comment]
How can we go further?
Any news?

**Comment by brunotl** [comment]
merged manually...

**Pull request closed without merging**
